# -*- coding: utf-8 -*-
"""btp2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnPE7EtiKrFzeKRmE-W8XWsHOv1YixR0
"""

! pip install sweetviz

import pandas as pd
import sweetviz as sv
t1 = pd.read_csv('/jan.csv')
t1.rename(columns = {'Value':'January'}, inplace = True)
t2 = pd.read_csv('/feb.csv')
c2= t2.Value
t1['Febuary'] = c2


t3 = pd.read_csv('/march.csv')
t4 = pd.read_csv('/april.csv')
t5 = pd.read_csv('/may.csv')
t6 = pd.read_csv('/june.csv')
t7 = pd.read_csv('/july.csv')
t8 = pd.read_csv('/aug.csv')
t9 = pd.read_csv('/sept.csv')
t10 = pd.read_csv('/oct.csv')
t11 = pd.read_csv('/nov.csv')
t12 = pd.read_csv('/dec.csv')
c2= t2.Value
c3= t3.Value
c4= t4.Value
c5= t5.Value
c6= t6.Value
c7= t7.Value
c8= t8.Value
c9= t9.Value
c10= t10.Value
c11= t11.Value
c12= t12.Value

t1['Febuary'] = c2
t1['March']=c3
t1['April'] = c4
t1['May'] = c5
t1['June']=c6
t1['July'] = c7
t1['August'] = c8
t1['September']=c9
t1['October'] = c10
t1['November'] = c11
t1['December']=c12

analyze_report = sv.analyze(t1)
analyze_report.show_html('analyze.html', open_browser=False)

import IPython
IPython.display.HTML('analyze.html')

t1 = pd.read_csv('/content/rainfall in india 1901-2015.csv')
analyze_report = sv.analyze(t1)
analyze_report.show_html('analyze.html', open_browser=False)

import IPython
IPython.display.HTML('analyze.html')

